export interface StockItem {
  ticker: string;
  name: string;
  sector: string;
}

export const CATALOG: StockItem[] = [
  { ticker: 'SPY',   name: 'S&P 500 ETF',           sector: 'ETF' },
  { ticker: 'QQQ',   name: 'Nasdaq 100 ETF',         sector: 'ETF' },
  { ticker: 'DIA',   name: 'Dow Jones ETF',          sector: 'ETF' },
  { ticker: 'IWM',   name: 'Russell 2000 ETF',       sector: 'ETF' },
  { ticker: 'AAPL',  name: 'Apple Inc.',              sector: 'Tecnologia' },
  { ticker: 'MSFT',  name: 'Microsoft Corp.',         sector: 'Tecnologia' },
  { ticker: 'GOOGL', name: 'Alphabet Inc.',           sector: 'Tecnologia' },
  { ticker: 'AMZN',  name: 'Amazon.com',              sector: 'Tecnologia' },
  { ticker: 'NVDA',  name: 'NVIDIA Corp.',            sector: 'Tecnologia' },
  { ticker: 'META',  name: 'Meta Platforms',          sector: 'Tecnologia' },
  { ticker: 'TSLA',  name: 'Tesla Inc.',              sector: 'Tecnologia' },
  { ticker: 'NFLX',  name: 'Netflix Inc.',            sector: 'Tecnologia' },
  { ticker: 'AMD',   name: 'Advanced Micro Devices',  sector: 'Tecnologia' },
  { ticker: 'INTC',  name: 'Intel Corp.',             sector: 'Tecnologia' },
  { ticker: 'CRM',   name: 'Salesforce Inc.',         sector: 'Tecnologia' },
  { ticker: 'ORCL',  name: 'Oracle Corp.',            sector: 'Tecnologia' },
  { ticker: 'ADBE',  name: 'Adobe Inc.',              sector: 'Tecnologia' },
  { ticker: 'UBER',  name: 'Uber Technologies',       sector: 'Tecnologia' },
  { ticker: 'SPOT',  name: 'Spotify Technology',      sector: 'Tecnologia' },
  { ticker: 'JPM',   name: 'JPMorgan Chase',          sector: 'Finanças' },
  { ticker: 'BAC',   name: 'Bank of America',         sector: 'Finanças' },
  { ticker: 'WFC',   name: 'Wells Fargo',             sector: 'Finanças' },
  { ticker: 'GS',    name: 'Goldman Sachs',           sector: 'Finanças' },
  { ticker: 'MS',    name: 'Morgan Stanley',          sector: 'Finanças' },
  { ticker: 'V',     name: 'Visa Inc.',               sector: 'Finanças' },
  { ticker: 'MA',    name: 'Mastercard Inc.',         sector: 'Finanças' },
  { ticker: 'SCHW',  name: 'Charles Schwab Corp.',   sector: 'Finanças' },
  { ticker: 'AXP',   name: 'American Express',        sector: 'Finanças' },
  { ticker: 'PYPL',  name: 'PayPal Holdings',         sector: 'Finanças' },
  { ticker: 'JNJ',   name: 'Johnson & Johnson',       sector: 'Saúde' },
  { ticker: 'UNH',   name: 'UnitedHealth Group',      sector: 'Saúde' },
  { ticker: 'PFE',   name: 'Pfizer Inc.',             sector: 'Saúde' },
  { ticker: 'ABBV',  name: 'AbbVie Inc.',             sector: 'Saúde' },
  { ticker: 'MRK',   name: 'Merck & Co.',             sector: 'Saúde' },
  { ticker: 'LLY',   name: 'Eli Lilly',               sector: 'Saúde' },
  { ticker: 'BMY',   name: 'Bristol-Myers Squibb',    sector: 'Saúde' },
  { ticker: 'AMGN',  name: 'Amgen Inc.',              sector: 'Saúde' },
  { ticker: 'XOM',   name: 'ExxonMobil Corp.',        sector: 'Energia' },
  { ticker: 'CVX',   name: 'Chevron Corp.',           sector: 'Energia' },
  { ticker: 'COP',   name: 'ConocoPhillips',          sector: 'Energia' },
  { ticker: 'SLB',   name: 'SLB (Schlumberger)',      sector: 'Energia' },
  { ticker: 'WMT',   name: 'Walmart Inc.',            sector: 'Consumo' },
  { ticker: 'KO',    name: 'Coca-Cola Co.',           sector: 'Consumo' },
  { ticker: 'PEP',   name: 'PepsiCo Inc.',            sector: 'Consumo' },
  { ticker: 'MCD',   name: "McDonald's Corp.",        sector: 'Consumo' },
  { ticker: 'SBUX',  name: 'Starbucks Corp.',         sector: 'Consumo' },
  { ticker: 'NKE',   name: 'Nike Inc.',               sector: 'Consumo' },
  { ticker: 'COST',  name: 'Costco Wholesale',        sector: 'Consumo' },
  { ticker: 'TGT',   name: 'Target Corp.',            sector: 'Consumo' },
  { ticker: 'BA',    name: 'Boeing Co.',              sector: 'Industrial' },
  { ticker: 'CAT',   name: 'Caterpillar Inc.',        sector: 'Industrial' },
  { ticker: 'GE',    name: 'GE Aerospace',            sector: 'Industrial' },
  { ticker: 'HON',   name: 'Honeywell Intl.',         sector: 'Industrial' },
  { ticker: 'MMM',   name: '3M Co.',                  sector: 'Industrial' },
  { ticker: 'UPS',   name: 'UPS Inc.',                sector: 'Industrial' },
  { ticker: 'T',     name: 'AT&T Inc.',               sector: 'Telecom' },
  { ticker: 'VZ',    name: 'Verizon Comm.',           sector: 'Telecom' },
  { ticker: 'DIS',   name: 'Walt Disney Co.',         sector: 'Telecom' },
  { ticker: 'CMCSA', name: 'Comcast Corp.',           sector: 'Telecom' },
  { ticker: 'XLU',   name: 'Utilities SPDR ETF',      sector: 'Utilidades' },
  { ticker: 'NEE',   name: 'NextEra Energy',          sector: 'Utilidades' },
  { ticker: 'DUK',   name: 'Duke Energy Corp.',       sector: 'Utilidades' },
  { ticker: 'SO',    name: 'Southern Company',        sector: 'Utilidades' },
  { ticker: 'AEP',   name: 'American Electric Power', sector: 'Utilidades' },
  { ticker: 'SRE',   name: 'Sempra Energy',           sector: 'Utilidades' },
  { ticker: 'XLRE',  name: 'Real Estate SPDR ETF',    sector: 'Imobiliário' },
  { ticker: 'AMT',   name: 'American Tower Corp.',    sector: 'Imobiliário' },
  { ticker: 'PLD',   name: 'Prologis Inc.',           sector: 'Imobiliário' },
  { ticker: 'EQIX',  name: 'Equinix Inc.',            sector: 'Imobiliário' },
  { ticker: 'SPG',   name: 'Simon Property Group',    sector: 'Imobiliário' },
  { ticker: 'O',     name: 'Realty Income Corp.',     sector: 'Imobiliário' },
];

export const SECTOR_COLORS: Record<string, string> = {
  'ETF':        'bg-purple-100 text-purple-700 dark:bg-purple-900/40 dark:text-purple-400',
  'Tecnologia': 'bg-blue-100 text-blue-700 dark:bg-blue-900/40 dark:text-blue-400',
  'Finanças':   'bg-emerald-100 text-emerald-700 dark:bg-emerald-900/40 dark:text-emerald-400',
  'Saúde':      'bg-pink-100 text-pink-700 dark:bg-pink-900/40 dark:text-pink-400',
  'Energia':    'bg-orange-100 text-orange-700 dark:bg-orange-900/40 dark:text-orange-400',
  'Consumo':    'bg-yellow-100 text-yellow-700 dark:bg-yellow-900/40 dark:text-yellow-400',
  'Industrial': 'bg-slate-100 text-slate-600 dark:bg-slate-700 dark:text-slate-300',
  'Telecom':      'bg-cyan-100 text-cyan-700 dark:bg-cyan-900/40 dark:text-cyan-400',
  'Utilidades':   'bg-teal-100 text-teal-700 dark:bg-teal-900/40 dark:text-teal-400',
  'Imobiliário':  'bg-amber-100 text-amber-700 dark:bg-amber-900/40 dark:text-amber-400',
};

export const SECTORS = [
  'Todos', 'ETF', 'Tecnologia', 'Finanças', 'Saúde',
  'Energia', 'Consumo', 'Industrial', 'Telecom', 'Utilidades', 'Imobiliário',
];
